// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

#nullable disable

namespace HamsterWars2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Defeats")
                        .HasColumnType("int");

                    b.Property<string>("FavoriteFood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Loves")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 1,
                            Defeats = 0,
                            FavoriteFood = "Chinese food",
                            ImageUrl = "/Content/Images/hamster-1.jpg",
                            Likes = 0,
                            Loves = "World of Warcraft",
                            Name = "Scooby",
                            TotalGames = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Defeats = 0,
                            FavoriteFood = "Broccoli",
                            ImageUrl = "/Content/Images/hamster-2.jpg",
                            Likes = 0,
                            Loves = "Rugby",
                            Name = "Shaggy",
                            TotalGames = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            Defeats = 0,
                            FavoriteFood = "Chicken and Rice",
                            ImageUrl = "/Content/Images/hamster-3.jpg",
                            Likes = 0,
                            Loves = "Football",
                            Name = "Fred",
                            TotalGames = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 1,
                            Defeats = 0,
                            FavoriteFood = "Pizza",
                            ImageUrl = "/Content/Images/hamster-4.jpg",
                            Likes = 0,
                            Loves = "Skateboarding",
                            Name = "George",
                            TotalGames = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 1,
                            Defeats = 0,
                            FavoriteFood = "Chinese food",
                            ImageUrl = "/Content/Images/hamster-5.jpg",
                            Likes = 0,
                            Loves = "Running",
                            Name = "Harry",
                            TotalGames = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 1,
                            Defeats = 0,
                            FavoriteFood = "McDonalds",
                            ImageUrl = "/Content/Images/hamster-6.jpg",
                            Likes = 0,
                            Loves = "Golfing",
                            Name = "Ron",
                            TotalGames = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            Age = 1,
                            Defeats = 0,
                            FavoriteFood = "Carrots",
                            ImageUrl = "/Content/Images/hamster-7.jpg",
                            Likes = 0,
                            Loves = "Sleeping",
                            Name = "Dumbledore",
                            TotalGames = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            Age = 1,
                            Defeats = 0,
                            FavoriteFood = "Pasta",
                            ImageUrl = "/Content/Images/hamster-35.jpg",
                            Likes = 0,
                            Loves = "Liseberg",
                            Name = "Göran",
                            TotalGames = 0,
                            Wins = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.MatchData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LoserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchesData");
                });
#pragma warning restore 612, 618
        }
    }
}
